import Libro from '#models/libro'

export default class LibroSeeder {
  public async run () {
    await Libro.createMany([
      {
        titulo: 'Cien años de soledad',
        autor: 'Gabriel García Márquez',
        anioPublicacion: 1967,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'El principito',
        autor: 'Antoine de Saint-Exupéry',
        anioPublicacion: 1943,
        genero: 'Fábula',
        activo: true,
      },
      {
        titulo: 'Don Quijote de la Mancha',
        autor: 'Miguel de Cervantes',
        anioPublicacion: 1605,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Rayuela',
        autor: 'Julio Cortázar',
        anioPublicacion: 1963,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Pedro Páramo',
        autor: 'Juan Rulfo',
        anioPublicacion: 1955,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'La sombra del viento',
        autor: 'Carlos Ruiz Zafón',
        anioPublicacion: 2001,
        genero: 'Misterio',
        activo: true,
      },
      {
        titulo: 'Ficciones',
        autor: 'Jorge Luis Borges',
        anioPublicacion: 1944,
        genero: 'Cuento',
        activo: true,
      },
      {
        titulo: 'La casa de los espíritus',
        autor: 'Isabel Allende',
        anioPublicacion: 1982,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Crónica de una muerte anunciada',
        autor: 'Gabriel García Márquez',
        anioPublicacion: 1981,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Sobre héroes y tumbas',
        autor: 'Ernesto Sabato',
        anioPublicacion: 1961,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'La tregua',
        autor: 'Mario Benedetti',
        anioPublicacion: 1960,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Aura',
        autor: 'Carlos Fuentes',
        anioPublicacion: 1962,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'El túnel',
        autor: 'Ernesto Sabato',
        anioPublicacion: 1948,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'La ciudad y los perros',
        autor: 'Mario Vargas Llosa',
        anioPublicacion: 1963,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Santa Evita',
        autor: 'Tomás Eloy Martínez',
        anioPublicacion: 1995,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'El amor en los tiempos del cólera',
        autor: 'Gabriel García Márquez',
        anioPublicacion: 1985,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'Los detectives salvajes',
        autor: 'Roberto Bolaño',
        anioPublicacion: 1998,
        genero: 'Novela',
        activo: true,
      },
      {
        titulo: 'La invención de Morel',
        autor: 'Adolfo Bioy Casares',
        anioPublicacion: 1940,
        genero: 'Ciencia ficción',
        activo: true,
      },
      {
        titulo: 'El Aleph',
        autor: 'Jorge Luis Borges',
        anioPublicacion: 1949,
        genero: 'Cuento',
        activo: true,
      },
      {
        titulo: 'La muerte de Artemio Cruz',
        autor: 'Carlos Fuentes',
        anioPublicacion: 1962,
        genero: 'Novela',
        activo: true,
      },
    ])
  }
}